/**
 * Writes src/buildInfo.ts: the commit this site was built from and the
 * day it was built, shown in the footer ("build 8f3a2c1 · 2026-10-01"),
 * so anyone can name the exact build they're looking at. Never hidden: on
 * Vercel the SHA comes from VERCEL_GIT_COMMIT_SHA, locally from git, and
 * with neither it says "local". Run before dev, test, typecheck and build
 * (package.json) and by Vite as it starts; nothing is fetched at runtime.
 *
 *   node scripts/build-info.mjs
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The short commit SHA: Vercel's, else git's, else "local". */
export function resolveSha(env = process.env, git = gitSha) {
  const full = env.VERCEL_GIT_COMMIT_SHA?.trim() || git();
  return full ? full.slice(0, 7) : "local";
}

function gitSha() {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

/** The build's date in UTC, YYYY-MM-DD. */
export function buildDate(now = new Date()) {
  return now.toISOString().slice(0, 10);
}

export function writeBuildInfo() {
  const info = { sha: resolveSha(), date: buildDate() };
  const out = new URL("../src/buildInfo.ts", import.meta.url);
  writeFileSync(
    out,
    `// Generated by scripts/build-info.mjs on every build. Don't edit.\nexport const buildInfo = ${JSON.stringify(info)} as const;\n`,
  );
  return info;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { sha, date } = writeBuildInfo();
  console.log(`build ${sha} · ${date}`);
}
