// Copies source/article.md into src/data/article.source.ts so the browser
// build and the node tests read the same transcript without a loader.
// Run after any change to source/article.md; article.test.ts fails until you do.
import { readFileSync, writeFileSync } from "node:fs";

const text = readFileSync(new URL("../source/article.md", import.meta.url), "utf8");
writeFileSync(
  new URL("../src/data/article.source.ts", import.meta.url),
  `// Generated by scripts/embed-article.mjs from source/article.md. Do not edit.\nexport const ARTICLE_SOURCE = ${JSON.stringify(text)};\n`,
);
