/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeftOpenRouteImport } from './routes/left-open'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeftOpenRoute = LeftOpenRouteImport.update({
  id: '/left-open',
  path: '/left-open',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/left-open': typeof LeftOpenRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/left-open': typeof LeftOpenRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/archive': typeof ArchiveIndexRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/left-open': typeof LeftOpenRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/archive/': typeof ArchiveIndexRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/left-open'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/archive/'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/left-open'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/archive'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/left-open'
    | '/sources'
    | '/timeline'
    | '/archive/$id'
    | '/chapters/$slug'
    | '/archive/'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeftOpenRoute: typeof LeftOpenRoute
  SourcesRoute: typeof SourcesRoute
  TimelineRoute: typeof TimelineRoute
  ArchiveIdRoute: typeof ArchiveIdRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/left-open': {
      id: '/left-open'
      path: '/left-open'
      fullPath: '/left-open'
      preLoaderRoute: typeof LeftOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeftOpenRoute: LeftOpenRoute,
  SourcesRoute: SourcesRoute,
  TimelineRoute: TimelineRoute,
  ArchiveIdRoute: ArchiveIdRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
