/**
 * Corrections to the post's published text: the only way it changes.
 *
 * source/article.md is the post as ingested, and never edited. An author
 * proposes a correction (through the CMS); the curator accepts or rejects
 * it, and applies an accepted one. An applied correction replaces its
 * passage's text (or a plate's caption) when the article is read, so the
 * change is a record with a reason, a date and who made it, and the
 * original stays in article.md.
 *
 * `proposed_text` is the passage as it should read, in the post's own
 * markdown: a paragraph's lines, a quote's lines with their "> ", a list's
 * items with their "- " (the same number of items), or a plate's caption.
 * An applied correction carries the narration script's words for the
 * passage too (`narration_text`; for a list, one paragraph per item), so the
 * spoken text keeps matching; the audio itself is regenerated by the
 * curator. One that resolves one of the post's discrepancies names it, and
 * the discrepancy lists it (src/model/validate.ts holds both rules).
 */
export type Correction = {
  /** Frozen: "c-" and a short random code the CMS fills in. */
  id: string;
  /** The passage ID ("2-p13") or plate ID ("plate-12") it corrects. */
  target: string;
  proposed_text: string;
  reason: string;
  /** The GitHub login of whoever proposed it, and when (YYYY-MM-DD). */
  proposed_by: string;
  date: string;
  status: "proposed" | "accepted" | "applied" | "rejected";
  /** Who accepted, applied or rejected it, and when: required once it leaves "proposed". */
  decided_by?: string;
  decided_on?: string;
  narration_text?: string;
  /** One of the post's discrepancies (src/data/discrepancies.json) it touches. */
  discrepancy?: string;
  /** Whether it settles that discrepancy, which must then be closed. */
  resolves_discrepancy?: boolean;
  /** Set once the curator has regenerated the passage's audio from the corrected script. */
  audio_regenerated?: boolean;
  /** The curator's, never shown to readers. */
  curator_note?: string;
};

/** The correction files, keyed by path ("./corrections/c-1a2b.json"), for the file-name check. */
export const correctionFiles = import.meta.glob("./corrections/*.json", {
  eager: true,
  import: "default",
}) as Record<string, Correction>;

export const corrections: Correction[] = Object.values(correctionFiles).sort(
  (a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id),
);

/** The applied correction each passage or plate reads by: the latest, if several. */
export const appliedCorrections = new Map(
  corrections.filter((c) => c.status === "applied").map((c) => [c.target, c]),
);
